#!/usr/bin/env bash
#
# One-command deployment for MERAVO onto a fresh Ubuntu server.
#
# Run it from inside the repository, on the server:
#
#   sudo bash deploy/setup-server.sh meravo.co.za
#
# It installs Docker if needed, writes a .env with freshly generated
# secrets, opens the firewall, and starts the site with HTTPS. Run it again
# any time to redeploy - it never overwrites an existing .env.

set -euo pipefail

DOMAIN="${1:-}"
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$REPO_DIR/.env"

bold() { printf "\n\033[1m%s\033[0m\n" "$1"; }
ok()   { printf "  \033[32m✓\033[0m %s\n" "$1"; }
warn() { printf "  \033[33m!\033[0m %s\n" "$1"; }
die()  { printf "\n\033[31m✗ %s\033[0m\n\n" "$1" >&2; exit 1; }

[ -n "$DOMAIN" ] || die "Usage: sudo bash deploy/setup-server.sh your-domain.co.za"
[ "$(id -u)" -eq 0 ] || die "Run this with sudo."

# Accept "www.example.co.za" but work with the bare domain: Caddy is
# configured for the apex and redirects www to it.
DOMAIN="${DOMAIN#http://}"; DOMAIN="${DOMAIN#https://}"; DOMAIN="${DOMAIN%%/*}"
DOMAIN="${DOMAIN#www.}"

bold "MERAVO deployment - $DOMAIN"

# ---------------------------------------------------------------- DNS check
bold "1/6  Checking DNS"
SERVER_IP="$(curl -s --max-time 10 https://api.ipify.org || true)"
[ -n "$SERVER_IP" ] || SERVER_IP="$(hostname -I | awk '{print $1}')"
echo "  this server: $SERVER_IP"

check_dns() {
  local host="$1"
  local got
  got="$(getent ahostsv4 "$host" 2>/dev/null | awk '{print $1}' | sort -u | tr '\n' ' ' || true)"
  if [ -z "$got" ]; then
    warn "$host does not resolve yet"
    return 1
  elif echo "$got" | grep -q "$SERVER_IP"; then
    ok "$host -> $got"
    return 0
  else
    warn "$host -> $got  (not this server)"
    return 1
  fi
}

DNS_OK=0
check_dns "$DOMAIN"     || DNS_OK=1
check_dns "www.$DOMAIN" || DNS_OK=1

if [ "$DNS_OK" -ne 0 ]; then
  cat <<EOF

  DNS is not pointing here yet. At your domain registrar, set:

      Type   Name   Value
      A      @      $SERVER_IP
      A      www    $SERVER_IP

  Remove any existing A/CNAME records for @ and www first, then wait a few
  minutes and run this script again.

  HTTPS cannot be issued until DNS resolves to this server.
EOF
  read -r -p "  Continue anyway? [y/N] " reply
  [[ "$reply" =~ ^[Yy]$ ]] || exit 1
fi

# ------------------------------------------------------------------- Docker
bold "2/6  Docker"
if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
  ok "already installed ($(docker --version | cut -d, -f1))"
else
  echo "  installing..."
  apt-get update -qq
  apt-get install -y -qq ca-certificates curl gnupg >/dev/null
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
    | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -qq
  apt-get install -y -qq docker-ce docker-ce-cli containerd.io \
    docker-buildx-plugin docker-compose-plugin >/dev/null
  systemctl enable --now docker >/dev/null 2>&1 || true
  ok "installed"
fi

# ---------------------------------------------------------------------- env
bold "3/6  Configuration"
if [ -f "$ENV_FILE" ]; then
  ok ".env already exists - leaving it untouched"
  warn "check SITE_DOMAIN and the PAYFAST_* values in it before going live"
else
  DB_PASS="$(openssl rand -base64 30 | tr -d '/+=' | head -c 32)"
  SECRET="$(openssl rand -base64 48 | tr -d '/+=' | head -c 64)"

  cat > "$ENV_FILE" <<EOF
# Generated by deploy/setup-server.sh on $(date -u +%Y-%m-%dT%H:%MZ)

SITE_DOMAIN=$DOMAIN
FRONTEND_PORT=8090
BACKEND_PORT=8000

ENABLE_API_DOCS=false
ENABLE_ACCOUNTS=false
RATE_LIMIT_PER_MINUTE=60

POSTGRES_USER=meravo
POSTGRES_PASSWORD=$DB_PASS
POSTGRES_DB=meravo

DATABASE_URL=postgresql+asyncpg://meravo:$DB_PASS@db:5432/meravo
SECRET_KEY=$SECRET
ACCESS_TOKEN_EXPIRE_MINUTES=60
BACKEND_CORS_ORIGINS=https://$DOMAIN,https://www.$DOMAIN

# ---- Payfast --------------------------------------------------------------
# Still the sandbox. Switch PAYFAST_MODE to "live" and paste your real
# merchant details once you have tested a sandbox payment end to end.
PAYFAST_MODE=sandbox
PAYFAST_MERCHANT_ID=10000100
PAYFAST_MERCHANT_KEY=46f0cd694581a
PAYFAST_PASSPHRASE=
PAYFAST_RETURN_URL=https://$DOMAIN/order-success
PAYFAST_CANCEL_URL=https://$DOMAIN/cart
PAYFAST_NOTIFY_URL=https://$DOMAIN/api/payments/payfast/notify

# ---- Order emails ---------------------------------------------------------
# Gmail needs an App password, not your normal password. See the README.
SMTP_HOST=
SMTP_PORT=587
SMTP_USERNAME=Heinrichcdoman@gmail.com
SMTP_PASSWORD=
SMTP_USE_TLS=true
MAIL_FROM=
MAIL_FROM_NAME=MERAVO
SHOP_OWNER_EMAIL=Heinrichcdoman@gmail.com
SHOP_CONTACT_PHONE=067 157 2670
STORE_URL=https://$DOMAIN

# ---- WhatsApp (optional) --------------------------------------------------
WHATSAPP_PROVIDER=
WHATSAPP_COUNTRY_CODE=27
WHATSAPP_PHONE_NUMBER_ID=
WHATSAPP_ACCESS_TOKEN=
WHATSAPP_TEMPLATE_NAME=order_confirmation
WHATSAPP_TEMPLATE_LANGUAGE=en
TWILIO_ACCOUNT_SID=
TWILIO_AUTH_TOKEN=
TWILIO_WHATSAPP_FROM=
TWILIO_CONTENT_SID=

VITE_API_BASE_URL=/api
EOF
  chmod 600 "$ENV_FILE"
  ok "wrote .env with a generated database password and secret key"
  warn "starts in Payfast SANDBOX mode - no real money moves until you change it"
fi

# ----------------------------------------------------------------- firewall
bold "4/6  Firewall"
if command -v ufw >/dev/null 2>&1; then
  ufw allow 22/tcp  >/dev/null 2>&1 || true
  ufw allow 80/tcp  >/dev/null 2>&1 || true
  ufw allow 443/tcp >/dev/null 2>&1 || true
  ufw --force enable >/dev/null 2>&1 || true
  ok "ports 22, 80 and 443 open; everything else closed"
else
  warn "ufw not installed - make sure ports 80 and 443 are open"
fi

# -------------------------------------------------------------------- build
bold "5/6  Building and starting"
cd "$REPO_DIR"
docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build
ok "containers started"

# ------------------------------------------------------------------- verify
bold "6/6  Checking the site"
echo "  waiting for the certificate and first boot (up to 2 minutes)..."
SITE_OK=0
for _ in $(seq 1 24); do
  code="$(curl -s -o /dev/null -w '%{http_code}' --max-time 8 "https://$DOMAIN/" || true)"
  api="$(curl -s -o /dev/null -w '%{http_code}' --max-time 8 "https://$DOMAIN/api/health" || true)"
  if [ "$code" = "200" ] && [ "$api" = "200" ]; then
    ok "https://$DOMAIN is live (site $code, api $api)"
    SITE_OK=1
    break
  fi
  sleep 5
done

if [ "$SITE_OK" -ne 1 ]; then
  warn "not answering on https yet"
  echo
  echo "  Look at the logs to see why:"
  echo "    docker compose -f docker-compose.yml -f docker-compose.prod.yml logs caddy | tail -30"
  echo "    docker compose -f docker-compose.yml -f docker-compose.prod.yml logs backend | tail -30"
  echo
  echo "  The usual cause is DNS not yet pointing at $SERVER_IP."
  exit 1
fi

cat <<EOF

$(bold "Done")
  Site       https://$DOMAIN
  Logs       docker compose -f docker-compose.yml -f docker-compose.prod.yml logs -f
  Restart    docker compose -f docker-compose.yml -f docker-compose.prod.yml restart
  Backup     docker compose exec -T db pg_dump -U meravo meravo | gzip > meravo-\$(date +%F).sql.gz

  Still to do before taking real money:
    1. Test a sandbox payment all the way through.
    2. Put your real Payfast details in .env and set PAYFAST_MODE=live.
    3. Add SMTP_PASSWORD (a Gmail App password) so order emails send.
    4. Re-run this script to apply those changes.

EOF
