"""add aramex shipping fields to orders

Revision ID: 66ff3d47e2a1
Revises: f869e1db8312
Create Date: 2026-09-05 09:15:54.313130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '66ff3d47e2a1'
down_revision: Union[str, None] = 'f869e1db8312'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'orders',
        sa.Column('subtotal_amount', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'),
    )
    op.add_column(
        'orders',
        sa.Column('shipping_fee', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'),
    )
    op.add_column(
        'orders',
        sa.Column('courier', sa.String(length=50), nullable=False, server_default='Aramex'),
    )
    op.add_column(
        'orders',
        sa.Column('tracking_number', sa.String(length=100), nullable=False, server_default=''),
    )
    # backfill subtotal_amount for any pre-existing orders (equal to total before shipping existed)
    op.execute('UPDATE orders SET subtotal_amount = total_amount WHERE subtotal_amount = 0')
    op.alter_column('orders', 'subtotal_amount', server_default=None)
    op.alter_column('orders', 'shipping_fee', server_default=None)
    op.alter_column('orders', 'courier', server_default=None)
    op.alter_column('orders', 'tracking_number', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'tracking_number')
    op.drop_column('orders', 'courier')
    op.drop_column('orders', 'shipping_fee')
    op.drop_column('orders', 'subtotal_amount')
    # ### end Alembic commands ###
